# PIXEL SETTINGS
WIDTH = 600
HEIGHT = 600
FPS = 60
BLOCK = 80

# COORDINATES
CENTER_1 = (WIDTH // 2 - BLOCK, HEIGHT // 2 - 30 - BLOCK, WIDTH // 2 + BLOCK, HEIGHT // 2 + 30 - BLOCK)
CENTER_2 = ((WIDTH + 100) // 2 - BLOCK + 20, HEIGHT // 2 - 30, WIDTH // 2 + BLOCK, HEIGHT // 2 + 30)
CENTER_3 = (WIDTH // 2 - BLOCK, HEIGHT // 2 - 30 + BLOCK, WIDTH // 2 + BLOCK, HEIGHT // 2 + 30 + BLOCK)
RIGHT_UP = (WIDTH - BLOCK + 80, 20)
RIGHT_UP_3 = (WIDTH - BLOCK + 80, 20 + BLOCK*2)
RIGHT_DOWN_1 = (WIDTH - BLOCK + 60, HEIGHT - BLOCK*4)
RIGHT_DOWN_2 = (WIDTH - BLOCK + 60, HEIGHT - BLOCK * 3)
RIGHT_DOWN_3 = (WIDTH - BLOCK + 60, HEIGHT - BLOCK*2)
RIGHT_DOWN_4 = (WIDTH - BLOCK + 60, HEIGHT - BLOCK)

RIGHT_CENTER = (WIDTH - BLOCK + 60, HEIGHT // 2 - 30 - BLOCK)
RIGHT_DOWN = (WIDTH - BLOCK, HEIGHT - BLOCK)
LEFT_UP = (0, 0)
LEFT_DOWN = (0, HEIGHT - BLOCK)
CENTER_DOWN = (WIDTH // 2 - BLOCK + 30, HEIGHT - BLOCK)
CENTER_DOWN_2 = (WIDTH // 2 - BLOCK + 30, HEIGHT - BLOCK + 40)

# PLOT PIXEL SETTINGS
DOT = (WIDTH-50) / 8
O_X = -3
O_Y = -1
# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (232, 232, 230)
LIGHT_BLUE = (104, 170, 234)
GREEN = (0, 200, 64)
YELLOW = (225, 225, 0)
PINK = (230, 50, 230)
RED = (255, 0, 0)

# Game states
MENU = 'menu'
TRAINING = 'training'
TESTING = 'testing'
REFRESH = 'refreshing'
UNDO = 'undoo'
TRAINING_PROCESS = 'training_process'
TESTING_PROCESS = 'testing_process'

# Path

TRAINING_PATH = './datasets/AAL_Label.csv'

# Button types

START_BUTTON = "start"
RETURN_BUTTON = "return"
INSERT_BUTTON = "insert"
DELETE_BUTTON = "delete"
REFRESH_BUTTON = "refresh"
UNDO_BUTTON = "undo"

# Button size
SMALL = 20
NORMAL = 30
BIG = 40

# COLOURS

BACKGROUND = GRAY
TEXT_COLOR = BLACK
BUTTON_TEXT_COLOR = WHITE
BUTTON_BACKGROUND = BLACK
BUTTON_OUTLINE = LIGHT_BLUE
LINE_COLOR = BLACK